import logo from "./logo.png"
import about from "./Aboutus-image.png"
import buggy from "./Buggy-Tour.png"
import cardImage from "./cardImage.jpg"
import cardImage1 from "./cardImage1.jpg"
import cardImage2 from "./cardImage2.jpg"
import cardImage3 from "./cardImage3.jpg"
import cardImage4 from "./cardImage4.jpg"
import cardImage5 from "./cardImage5.jpg"
import cardImage6 from "./cardImage6.jpg"
import topBanner from "./Home-Top-Banner.jpg"
import desertExtreme from "./desert-xtreme-logo.png"
import mobileLogo from "./mobile-logo.png"
import mobileTopBanner from "./Tripatour-Image.jpg"
import category1 from "./category-01.png"
import category2 from "./category-02.png"
import category3 from "./category-03.png"
import category4 from "./category-04.png"
import category5 from "./category-05.png"

export {logo,about,buggy,cardImage,cardImage1,cardImage2,cardImage3,cardImage4,cardImage5,cardImage6,topBanner,desertExtreme,mobileLogo,mobileTopBanner,category1,category2,category3,category4,category5}